### ISSUE TITLE
ef-auturm org-mode todo keywords color not distinguish

### ISSUE THREAD

**Issue by Spike-Leung** [protesilaos/ef-themes#1]
![image](https://user-images.githubusercontent.com/30440218/184863115-f91a5e95-c765-44f1-b679-4a00e1d3cce5.png)

I have updated to the latest commit (08b95a4 Tweak tooltip face)

**Comment by protesilaos** [comment]
I am testing `ef-autumn` now.  Made these changes:

![Screenshot from 2022-08-16 15-01-13](https://user-images.githubusercontent.com/12828033/184874674-d10df50c-5ce5-4f03-b530-36e55ec8d97c.png)

There still are some conflicts with lower-level headings, though I think that is okay.  What do you think?

**Comment by Spike-Leung** [comment]
Cool, thanks：）Your theme looks great!
