### ISSUE TITLE
ef-themes-with-colors throws error

### ISSUE THREAD

**Issue by stevemolitor** [protesilaos/ef-themes#11]
Executing the example code in section "9. Use colors from the active Ef theme":

```emacs-lisp
(ef-themes-with-colors
 (list bg-main fg-main bg-mode-line cursor))
```

Gives this error:

```
Symbol’s value as variable is void: ef-light-palette
```

The error happens [here](https://git.sr.ht/~protesilaos/ef-themes/tree/main/ef-themes.el#L1503). It seems to have been introduced in this commit: e5e8ada5bbdff29f2da40a6cefe1c16dff6b17ed. The [ef-light-pallette](https://git.sr.ht/~protesilaos/ef-themes/tree/main/ef-light-theme.el#L42) constant has not been defined yet apparently. 

If I select the `ef-light-theme` first then it works fine (which makes sense).

**Comment by protesilaos** [comment]
Thank @stevemolitor!  Your assessment is correct.  I need to think about an elegant way to do this.  Will think about it some more and report back to you.

**Comment by protesilaos** [comment]
Maybe you can try this diff?

```diff
 ef-themes.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ef-themes.el b/ef-themes.el
index 9a60504..377935c 100644
--- a/ef-themes.el
+++ b/ef-themes.el
@@ -1518,7 +1518,7 @@ (defmacro ef-themes-with-colors (&rest body)
          ;; instantiate the actual theme's palette.  We have to do this
          ;; otherwise the macro does not work properly when called from
          ;; inside a function.
-         (colors (mapcar #'car (symbol-value 'ef-light-palette))))
+         (colors (mapcar #'car (ef-themes--current-theme-palette))))
     `(let* ((c '((class color) (min-colors 256)))
             (,sym (ef-themes--current-theme-palette))
             ,@(mapcar (lambda (color)
```

I tested it with these:

```elisp
(defun testing-ef-themes-with-colors ()
  (ef-themes-with-colors
    (list bg-main)))

;; Evaluate these, change theme and eval again to see if you get a
;; different value:
(ef-themes-with-colors (list bg-main))

(testing-ef-themes-with-colors)
```

**Comment by protesilaos** [comment]
Thank you!  Just pushed the change.  Closing this now.
