### ISSUE TITLE
`ef-themes--current-theme` doesn't work in combination with `smart-mode-line`

### ISSUE THREAD

**Issue by joncol** [protesilaos/ef-themes#12]
I use the following:

```emacs-lisp
(use-package smart-mode-line
  :config
  (setq sml/no-confirm-load-theme t)
  (sml/setup)
  (sml/apply-theme 'dark))
```

This leads to an error when trying to call `ef-themes--current-theme`.

Note that the value of `custom-enabled-themes` is `(smart-mode-line-dark ef-autumn)` in my case. It looks like `ef-themes--current-theme` assumes the `ef-theme` should be the first element of the `custom-enabled-themes` list. Is this an intentional assumption, and I should be applying my themes in some other order?

**Comment by protesilaos** [comment]
> From: Jonas Collberg ***@***.***>
> Date: Tue, 30 Aug 2022 02:42:08 -0700

[ Note that smart-mode-line is not supported right now. ]

> I use the following:
>
> ```emacs-lisp
> (use-package smart-mode-line
>   :config
>   (setq sml/no-confirm-load-theme t)
>   (sml/setup)
>   (sml/apply-theme 'dark))
> ```
>
> This leads to an error when trying to call `ef-themes--current-theme`.

I see.  So sml is seting itself up as a "theme"?

> Note that the value of `custom-enabled-themes` is
> `(smart-mode-line-dark ef-autumn)` in my case. It looks like
> `ef-themes--current-theme` assumes the `ef-theme` should be the first
> element of the `custom-enabled-themes` list. Is this an intentional
> assumption, and I should be applying my themes in some other order?

Yes, this is intentional.  Though it may still be bad design that we
need to review.  There is no compelling reason why it should be the
first element.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by joncol** [comment]
> I see.  So sml is seting itself up as a "theme"?

Yes, it seems so.

> Yes, this is intentional.  Though it may still be bad design that we
need to review.  There is no compelling reason why it should be the
first element.

OK!

**Comment by protesilaos** [comment]
Hello again @joncol!

Does this diff work for you?  I will try it with everything else tomorrow morning to test if it needs anything else.  Will also look into smart-mode-line.

```diff
 ef-themes.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/ef-themes.el b/ef-themes.el
index 377935c..a3fbd29 100644
--- a/ef-themes.el
+++ b/ef-themes.el
@@ -319,7 +319,7 @@ (defun ef-themes--list-known-themes ()
 
 (defun ef-themes--current-theme ()
   "Return first enabled Ef theme."
-  (when-let* ((theme (car custom-enabled-themes)))
+  (when-let* ((theme (car (ef-themes--list-enabled-themes))))
     (if (memq theme (ef-themes--list-enabled-themes))
         theme
       (user-error "`%s' is not an Ef theme" theme))))
```

**Comment by joncol** [comment]
That diff works, yes :+1:

**Comment by protesilaos** [comment]
Thank you!  I bumped the version to 0.4.1 so that the GNU ELPA package gets rebuilt.  Though this will be documented in the release notes for 0.5.0.

**Comment by joncol** [comment]
Btw, it seems a bit unnecessary to do the `memq` check just after binding `theme` in the code above, no?

**Comment by protesilaos** [comment]
Indeed!  We probably don't need the `user-error` now, anyway:

```diff
 ef-themes.el | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

diff --git a/ef-themes.el b/ef-themes.el
index 3e8bf84..d5347a2 100644
--- a/ef-themes.el
+++ b/ef-themes.el
@@ -320,9 +320,7 @@ (defun ef-themes--list-known-themes ()
 (defun ef-themes--current-theme ()
   "Return first enabled Ef theme."
   (when-let* ((theme (car (ef-themes--list-enabled-themes))))
-    (if (memq theme (ef-themes--list-enabled-themes))
-        theme
-      (user-error "`%s' is not an Ef theme" theme))))
+    theme))
 
 (defun ef-themes--palette (theme)
   "Return THEME palette as a symbol."
```

Thoughts?

**Comment by joncol** [comment]
Looks nice! :+1:

**Comment by protesilaos** [comment]
Done.  Thank you!
