### ISSUE TITLE
Hello, i'm curious regarding color-customization

### ISSUE THREAD

**Issue by Kenneth-Mata** [protesilaos/ef-themes#16]
I'm following the ef-themes manual and i'm trying to integrate it with lambda-line, in particular, a way to change the color of visual bell (a blink like visible-bell that happens across the mode-line), right now is a very bright red and would like something more dark, so far i have this code 
```
(defun my-ef-themes-custom-faces()
  "My customizations on top of the Ef themes."
  (ef-themes-with-colors (custom-set-faces
                          `(lambda-line-visual-bell ((,c :background "#470010"))))))
(add-hook 'ef-themes-post-load-hook #'my-ef-themes-custom-faces)
``` i would like some guidance regarding how to do this. thank you.

**Comment by protesilaos** [comment]
Hello @Kenneth-Mata!

The code you have looks correct.  It does not work for you?  Or do you need to replace the colour value with a variable from the themes' palette?

If it does not work, maybe it is because lambda-line is a package that gets loaded before the theme?  Does your customisation take effect if you re-load the theme?

**Comment by Kenneth-Mata** [comment]
Hello, i tried a few things, disabling and loading theme or line didn't work, also tried wrapping the function mentioned before with ``with-eval-after-load`` and having :after in use-package, so that lambda line loads after ef-themes

**Comment by protesilaos** [comment]
Perhaps you are not loading the theme with one of the relevant commands that call `ef-themes-post-load-hook`.

For example:

```elisp
;; Load the theme and run `ef-themes-post-load-hook'
(ef-themes-select 'ef-dark) ; Instead of (load-theme 'ef-dark :no-confirm)
```

I am now trying your code and it works as intended.  Using it with `ef-dark` theme:

![Screenshot from 2022-09-10 02-32-07](https://user-images.githubusercontent.com/12828033/189458955-6efbd1dc-7f9b-448a-b251-6b34242023e9.png)

**Comment by Kenneth-Mata** [comment]
It works now!, i changed to ef-theme-select and works as intended now, thank you very much.

**Comment by protesilaos** [comment]
You are welcome!  I will try to improve the documentation to make this more obvious.
