### ISSUE TITLE
setting heights in ef-themes-headings, prevents headings from scaling by text-scale

### ISSUE THREAD

**Issue by Inc0n** [protesilaos/ef-themes#17]
For example, something like this:
```
(setq ef-themes-headings
	  ;; This variable pitch does not scale, which works badly in NOV
	  '((1 . (bold variable-pitch 1.2))
		(2 . (regular variable-pitch 1.14))
		(3 . (variable-pitch 1.1))
		(t . (variable-pitch))
		))
```

The content (text that are not headings) scales fine, now headings ~level 1, 2, 3~ (my testing just now shows it is all headings) will stay the same size even with `text-scale-adjust`.
Is this an understood behaviour, if not is there any work arounds or fixes?

**Comment by Inc0n** [comment]
It's best demonstrate this with a screen shot:
<img width="321" alt="Screenshot 2022-10-03 at 17 43 14" src="https://user-images.githubusercontent.com/33980911/193632623-55a1ec4d-43e6-4c1e-8301-a8caecb5134e.png">

This org buffer has been text scaled, the `ef-themes-headings` are configured in the post. It can be seen that all text that are not headings are noticably bigger. And all headings are remained on their fixed size.

**Comment by protesilaos** [comment]
Hello @Inc0n!  It works on my end:

![Screenshot from 2022-10-03 20-02-23](https://user-images.githubusercontent.com/12828033/193636173-ca92dd02-2e8b-494d-855e-2d38a21b8fd7.png)

Increasing the scale for effect:

![Screenshot from 2022-10-03 20-02-32](https://user-images.githubusercontent.com/12828033/193636177-59b7db9b-9b17-4353-bb18-aaf910255eed.png)

Can you do `M-x describe-face` and check `variable-pitch`?  Maybe it has an absolute height value (e.g `100`) whereas it should be a floating point.

**Comment by protesilaos** [comment]
I forgot `text-scale-adjust`, which works again:

![Screenshot from 2022-10-03 20-04-29](https://user-images.githubusercontent.com/12828033/193636463-666d2a89-27aa-4577-98ae-b09b8f55d2ff.png)

**Comment by Inc0n** [comment]
Ah, I see, Thanks. So it must be my own setup, 
> variable-pitch? Maybe it has an absolute height value (e.g 100) whereas it should be a floating point.

You are right, I have set it to 140 on my end. So as you suggest, should it be something like 1.4?

Since this is a problem with my own config, I will close this first.

**Comment by Inc0n** [comment]
Thanks Prot, I have changed them to a floating point, it works now!

**Comment by protesilaos** [comment]
You are welcome!

If you ever need to have presets of font configurations, check my `fontaine` package.

**Comment by Inc0n** [comment]
Ahh, that looks very handy! 👍🤝
