### ISSUE TITLE
Parenthesis in org-block are not using fixed pitch

### ISSUE THREAD

**Issue by zealotrush** [protesilaos/ef-themes#19]
Hi, Prot

As stated in the title, parenthesis (including `()`, `[]` and `{}`, but not `<>`) in org-block are not using fixed-pitch faces.  It seems like a bug.  Here is a screenshot for demonstrating this issue.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/2275580/202607359-f878be78-306e-4fd9-8ed0-8b4b0946d978.png">

PS: this issue doesn't exist in c-mode.
PPS: modus-themes doesn't have this issue.

**UPDATE**

I found that it is related to the *tree-sitter* package I'm using.  Ef-themes doesn't support this package, while modus-themes does.  So, this should not be think of as a bug, rather a missing feature, I guess.

**Comment by protesilaos** [comment]
Hello @zealotrush!

I also notice that there is a white background behind them, which suggests that something else is also in effect.  When I type this code on my end, I do not get that white background.

**Comment by zealotrush** [comment]
> Hello @zealotrush!
> 
> I also notice that there is a white background behind them, which suggests that something else is also in effect. When I type this code on my end, I do not get that white background.

Thanks!  I totally missed the white background.  By pressing `C-u C-x =` with the cursor placing on the `(` character, I found the faces are:

      (rainbow-delimiters-depth-1-face tree-sitter-hl-face:punctuation.bracket org-block)

Then, by clicking on the `tree-sitter-hl-face:punctuation.bracket` entry, I got:

```
Defined in ‘org-faces.el’.
...
       Background: #f7f9f9
...
          Inherit: ef-themes-fixed-pitch
```

I guess this is where the white background comes from.

**Comment by protesilaos** [comment]
Very well!  Please tell me how you enable tree-sitter so I can take a look.

**Comment by zealotrush** [comment]
Here is my tree-sitter related config.

```
(use-package tree-sitter
  :defer t
  :config (global-tree-sitter-mode)
  :hook (tree-sitter-after-on . tree-sitter-hl-mode))
(use-package tree-sitter-langs)
```

**Comment by protesilaos** [comment]
Thank you!  I just added support for the `tree-sitter` faces.  The problem was that the underlying face inherited from `default`, hence the `variable-pitch` and the use of the main background.

Please confirm that the change fixes the issue on your end.

**Comment by zealotrush** [comment]
> Please confirm that the change fixes the issue on your end.

It's fixed now.  Thank you!

<img width="298" alt="image" src="https://user-images.githubusercontent.com/2275580/202617027-fe0afbc5-08d3-49e4-a27f-8be4c5f34fd6.png">

**Comment by protesilaos** [comment]
Great!
