### ISSUE TITLE
Ediff colors not displaying

### ISSUE THREAD

**Issue by goldfita** [protesilaos/ef-themes#20]
Hi, I'm hoping to replace doom-themes/doom-dark+ for a number of reasons, one of which is that ediff colors are too faint. I found modus-vivendi and ef-dark to have a similar appearance to dark+. But I can't get colors to display with ediff, which it says is supported. I have dimmer, but it's disabled when starting ediff. I could use modus-vivendi since they are so similar, but I like having the colors in the modeline.

![ef](https://github.com/protesilaos/ef-themes/assets/25371142/9fea1075-838b-4e4d-a202-19bc843e5eaa)
ef-dark (v0.11.0)

![modus](https://github.com/protesilaos/ef-themes/assets/25371142/6d9fe793-09c8-4d7f-981d-0f6534e2b5d6)
modus-vivendi

**Comment by protesilaos** [comment]
Thank you @goldfita!  I just made the change.  A new version of the package will be available in a few hours (unless you are building directly from Git).

**Comment by goldfita** [comment]
Amazing! It's hardly even been a day. It looks good.

**Comment by protesilaos** [comment]
Great!  We can safely close this now.
