### ISSUE TITLE
Feature request: support Centaur Tabs

### ISSUE THREAD

**Issue by amodelbello** [protesilaos/ef-themes#21]
Hello,
Thanks for the really beautiful themes. I was wondering if you would consider supporting Centaur Tabs (https://github.com/ema2159/centaur-tabs).

<img width="948" alt="Screen Shot 2023-06-03 at 7 33 41 PM" src="https://github.com/protesilaos/ef-themes/assets/2342804/8df464d5-1314-47dd-8888-b60f1f40e03d">

**Comment by protesilaos** [comment]
Hello @amodelbello!  I did it just now.  Please let me know if it works for you.

**Comment by amodelbello** [comment]
Wow! Thanks for the quick response. 
I pasted the changes but unfortunately I'm still seeing dark tabs for the light themes.

**Comment by protesilaos** [comment]
> From: Amo DelBello ***@***.***>
> Date: Sat,  3 Jun 2023 23:22:29 -0700
>
> Wow! Thanks for the quick response. 

You are welcome!

> I pasted the changes but unfortunately I'm still seeing dark tabs for
> the light themes.

Maybe pasting the changes does not do the trick.  Can you try to pull
the latest package from GNU-devel ELPA?  If you don't know how to do it,
I will give you the instructions.

Then restart Emacs and test it again.

Centaur is working with all themes on my end.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
You are welcome!
