### ISSUE TITLE
question about core themes integration

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/ef-themes#23]
hi prot. i hope you are doing well

i was just wondering whether there were plans to integrate ef into core emacs - as was modus

**Comment by protesilaos** [comment]
Hello @gitrj95!

> hi prot. i hope you are doing well

I am fine, thank you!  I hope the same goes for you.

> i was just wondering whether there were plans to integrate ef into core emacs - as was modus

I don't think so.  These decisions are not up to me.  There has to be a discussion on the emacs-devel mailing list: the maintainers will decide.  This is how it was done for the modus-themes as well.  I simply agreed when they asked me if I was okay with that.

**Comment by zoliky** [comment]
I had the same thought. Incorporating the EF themes into the Emacs core would be a fantastic addition. I hope someone raises this topic on the Emacs devel list since I'm not a member of it.

**Comment by protesilaos** [comment]
@zoliky As far as I know, the emacs-devel mailing list is not subscriber based for posting purposes: anyone can send an email there.  If you think this is worth discussing with the Emacs maintainers, send an email to <emacs-devel@gnu.org>.

**Comment by gitrj95** [comment]
closing as there's a path forward. thanks as always, prot
