### ISSUE TITLE
Low contrast between minibuffer-prompt and help-key-binding faces in ef-elea-* themes

### ISSUE THREAD

**Issue by stevemolitor** [protesilaos/ef-themes#24]
This is an edge case. The contrast between the `minibuffer-prompt` and the `help-key-binding` faces is very low in `ef-elea-dark`. In the gif below `C-g` uses the `help-key-binding` face:

![](https://cdn.zappy.app/e09fbfd72935930684b01620cf584276.png)

It's a _little_ better in `ef-elea-light` but not great:

![](https://cdn.zappy.app/f4c8b5e3dadfa658f2f6b3745a194632.png)

The contrast is great in the other themes I tested. Here's `ef-dark` and `ef-kassio`:

![](https://cdn.zappy.app/4cde60c2496c3d33b25b792afb3a973a.png)

![](https://cdn.zappy.app/d822e31bdacc60a2748644c32f70d4fb.png)

**Comment by protesilaos** [comment]
Hello @stevemolitor!  I can see the following themes as potentially problematic for this case:

- ef-bio
- ef-day
- ef-deuteranopia-dark
- ef-duo-light
- ef-elea-dark (they are the same colour)
- ef-elea-light (as above)
- ef-frost
- ef-night

Of those, the Elea variants definitely need to be considered.  The others may be fine as-is.  I am testing things with this:

```elisp
(read-string
 (format "Request for AI overloards (%s to stop): "
         (propertize "C-g" 'face 'help-key-binding)))
```

**Comment by stevemolitor** [comment]
Thanks @protesilaos! It's definitely an edge case but I appreciate it.

> I am testing things with this:
> 
> ```emacs-lisp
> (read-string
>  (format "Request for AI overloards (%s to stop): "
>          (propertize "C-g" 'face 'help-key-binding)))
> ```

👍 Good test case. That reproduces my issue perfectly.

**Comment by protesilaos** [comment]
I just pushed the changes.  Please let me know if they work for you.

**Comment by stevemolitor** [comment]
Works great, thanks!

![](https://cdn.zappy.app/20a0c9cfc9be707e36c28cc8026e6f7e.png)

**Comment by protesilaos** [comment]
Very well!  We can safely close this now.
