### ISSUE TITLE
wcag aa label

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/ef-themes#26]
hi prot. i was just wondering if it made sense to provide a similar label to this repo as you do to the modus repo regarding the legibility standards. wcag aa is still strong relative to most themes out there - i only found references to its standard adherence in the bowels of its manual, but i think it's valuable to call out in the repo headline and readme, too. what do you think?

**Comment by protesilaos** [comment]
You mean to add it in the description of the repository?  It does make sense to mention this fact.

**Comment by gitrj95** [comment]
yes. this is what i mean
