### ISSUE TITLE
Inactive shade when using zsh-autosuggestions.

### ISSUE THREAD

**Issue by theherk** [protesilaos/ef-themes#3]
Awesome themes, Prot. I know you don't intend to support every edge case and that is totally cool, but I wonder if there is some "inactive" face or some such that isn't addressed herein. When using vterm with a zsh session using the plugin [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) it tries to autocomplete like fish. The suggestions is some muted face, but using these dark themes, the suggested text is invisible. In the light versions, it is visible.

Here you can see it in summer.

![Summer](https://user-images.githubusercontent.com/3605078/185462717-0c92a125-e99a-4ea5-adc0-6d2d7dff7e42.png)

Here it looks like it isn't there (but it really is) in autumn.

![Autumn](https://user-images.githubusercontent.com/3605078/185462725-eadc53a1-767d-44a9-9c98-fb2fd45976aa.png)

**Comment by protesilaos** [comment]
Hello @theherk!

> Awesome themes, Prot.

Thank you!

> The suggestions is some muted face, but using these dark themes, the suggested text is invisible. In the light versions, it is visible.

Oh, that is unusable!  I took a very quick look at the repo you linked to.  My understanding is that it uses some ANSI escape sequence instead of an Emacs face.  Right?  Perhaps they are hardcoding it to termcolor0, which would be black?

Put differently, and for me to understand this better: (i) do those autosuggestions work in a generic terminal emulator, and (ii) do they work with a black/dark background in that context?

Maybe other dark Emacs themes render those correctly?  We can learn more from them.

As for the suggested text, please place the point over one of its characters and do `M-x describe-char` (or type `C-u C-x =`).  It will produce a Help buffer which includes information about any applicable face.  We can use that.

**Comment by theherk** [comment]
Here is the `describe-char` output:

```
             position: 63 of 85 (73%), column: 17
            character: o (displayed as o) (codepoint 111, #o157, #x6f)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x6F
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Strong L2R, a:ASCII, l:Latin, r:Roman
             to input: type "C-x 8 RET 6f" or "C-x 8 RET LATIN SMALL LETTER O"
          buffer code: #x6F
            file code: #x6F (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    mac-ct:-*-VictorMono Nerd Font-normal-normal-normal-*-20-*-*-*-p-0-iso10646-1 (#x52)

Character code properties: customize what to show
  name: LATIN SMALL LETTER O
  general-category: Ll (Letter, Lowercase)
  decomposition: (111) ('o')

There are text properties here:
  font-lock-face       (:foreground "black" :extend t)
  fontified            t
  ws-butler-chg        chg
```

I think you're correct though, it does seem to be the color no matter what. Here are examples in [wezterm](https://wezfurlong.org/) using theme "nord" and "nord-light". It does always seem to be the same color. I will close this. I didn't realize this was a constant color. Thank you for the quick reply.

![nord](https://user-images.githubusercontent.com/3605078/185466046-e5bde51a-4834-4a6b-9290-92d74e013054.png)
![nord-light](https://user-images.githubusercontent.com/3605078/185466054-a2928c0d-b8e3-4614-b67b-fb9dd8729176.png)

**Comment by protesilaos** [comment]
You are welcome!  It would still be interesting to figure out why they hardcode it that way.  Maybe you could bring this to the attention of the maintainers?  Ideally with a reproducible recipe that does not involve Emacs?  Why not use, say, termcolor6 (cyan) instead?  Sure, it won't be the prettiest in all contexts, but it will definitely be better than invisible text.

**Comment by theherk** [comment]
Sometimes, ~~we~~ I just overlook the most obvious things. I didn't even consider that this was configurable until I couldn't see it... and I've used this for quite some time. :) Turns out [it is configurable](https://github.com/zsh-users/zsh-autosuggestions#configuration).

**Comment by protesilaos** [comment]
Ah, that makes sense.  I am still curious to see what colour value is returned by, say, `fg=6`.  Emacs has some support for ANSI escape sequences, so maybe this is something that is already supported or could be done easily.

**Comment by theherk** [comment]
`fg=6` actually looks marvelous.

![Screenshot 2022-08-18 at 20 32 17](https://user-images.githubusercontent.com/3605078/185468512-f220254f-a817-4638-be04-948fcca4fea4.png)

**Comment by protesilaos** [comment]
Very well!  This means that it picks from the Emacs colours.  I am not sure which one, but it has to be either the `ansi-color` or `term` faces that I already support.
