### ISSUE TITLE
mu4e faces make flagged and trashed messages look the same

### ISSUE THREAD

**Issue by alphapapa** [protesilaos/ef-themes#32]
Hi Prot,

I just noticed that in `ef-themes` the `mu4e-flagged-face` looks the same as the `mu4e-trashed-face`.  This is a bit confusing when a list of messages has both types in it.

What do you think?

Thanks for your work on these themes!

**Comment by protesilaos** [comment]
Thank you @alphapapa!

I just made a change. Please let me know if it works for you.

**Comment by alphapapa** [comment]
Thanks, Prot!
