### ISSUE TITLE
Light vs Dark Theme Customizations

### ISSUE THREAD

**Issue by stevemolitor** [protesilaos/ef-themes#33]
I'd like to apply certain customizations based on whether the current ef-theme is a light or a dark theme. Specifically, I have downloaded two versions of the same font with slightly different weights (400 vs 450). I'd like to use the lighter version for dark themes, and the heavier font for light themes.

Is there a convenient way to do that? I could imagine that people might want other little tweaks based on light vs dark. 

Thanks, and thanks again for the wonderful themes!

**Comment by protesilaos** [comment]
Hello Steve!

> From: Steve Molitor ***@***.***>
> Date: Tue, 28 Nov 2023 06:24:48 -0800
>
> I'd like to apply certain customizations based on whether the current
> ef-theme is a light or a dark theme. Specifically, I have downloaded
> two versions of the same font with slightly different weights (400 vs
> 450). I'd like to use the lighter version for dark themes, and the
> heavier font for light themes.
>
> Is there a convenient way to do that? I could imagine that people
> might want other little tweaks based on light vs dark.

Do you have the code ready for the fonts? Assuming you do, just replace
the following 'message' calls below.

    (defun my-ef-themes-config-per-variant (theme)
      (cond
       ((memq theme ef-themes-dark-themes)
        (message "The %s is dark" theme))
       ((memq theme ef-themes-light-themes)
        (message "The %s is light" theme))
       (t
        (message "The %s is not an Ef theme" theme))))

    (add-hook 'enable-theme-functions #'my-ef-themes-config-per-variant)

Otherwise, tell me what you need exactly and I can tweak the code
accordingly.

> Thanks, and thanks again for the wonderful themes!

You are welcome!

All the best,
Protesilaos (or simply "Prot")

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by stevemolitor** [comment]
`(memq theme ef-themes-dark-themes)` was what I was looking for, thanks @protesilaos!
