### ISSUE TITLE
ef-themes inherits faces from modus-themes

### ISSUE THREAD

**Issue by marasenna** [protesilaos/ef-themes#34]
Ef-themes version: 1.4.0

In `ef-themes.el`:
``` elisp
`(ediff-fine-diff-Ancestor ((,c :inherit modus-themes-subtle-cyan)))                                                                                                                      
`(tab-bar ((,c :inherit modus-themes-ui-variable-pitch :background ,bg-tab-bar)))                                                                                                 
`(tab-line ((,c :inherit modus-themes-ui-variable-pitch :background ,bg-tab-bar :height 0.95)))                                                                                           
`(whitespace-empty ((,c :inherit modus-themes-intense-magenta)))                                                                                                                          
`(whitespace-space-after-tab ((,c :inherit modus-themes-subtle-magenta)))                                                                                                                 
`(whitespace-space-before-tab ((,c :inherit modus-themes-subtle-cyan)))
```
I think `tab-bar` and `tab-line` should inherit from `ef-themes-ui-variable-pitch`. However, for the rest ef-themes has no subtle and intense faces.

**Comment by protesilaos** [comment]
> From: P M ***@***.***>
> Date: Thu,  7 Dec 2023 04:33:33 -0800
>
> Ef-themes version: 1.4.0
>
> In `ef-themes.el`:
> ``` elisp
> `(ediff-fine-diff-Ancestor ((,c :inherit modus-themes-subtle-cyan)))                                                                                                                      
> `(tab-bar ((,c :inherit modus-themes-ui-variable-pitch :background ,bg-tab-bar)))                                                                                                 
> `(tab-line ((,c :inherit modus-themes-ui-variable-pitch :background ,bg-tab-bar :height 0.95)))                                                                                           
> `(whitespace-empty ((,c :inherit modus-themes-intense-magenta)))                                                                                                                          
> `(whitespace-space-after-tab ((,c :inherit modus-themes-subtle-magenta)))                                                                                                                 
> `(whitespace-space-before-tab ((,c :inherit modus-themes-subtle-cyan)))
> ```
>
> I think `tab-bar` and `tab-line` should inherit from
> `ef-themes-ui-variable-pitch`. However, for the rest ef-themes has no
> subtle and intense faces.

Thank you! I thought I had fixed this before, but apparently I did not.
Just pushed the changes now.

-- 
Protesilaos Stavrou
https://protesilaos.com
