### ISSUE TITLE
Foreground color in imenu-list

### ISSUE THREAD

**Issue by newhallroad** [protesilaos/ef-themes#35]
Thank you for your magnificent work on emacs. I use your work more or less every day and I appreciate your packages and your meticulous documentation.

I use the [imenu-list ](https://github.com/bmag/imenu-list) package to provide a sidebar buffer with the imenu entries of the buffer I am editing. I typically use this when I am writing text in markdown. In ef-themes, the foreground colors of the imenu-list buffer do not match the face of the headings in the markdown buffer. It seems that imenu-list is not affected by ef-themes, while the markdown headers are.

I solved/hacked the problem with the settings below, which I put in the `:config` block of my use-package configuration for imenu-list, but perhaps you would be interested in making a more sustainable fix in the ef-themes code.

Many, many thanks.

```
  (set-face-attribute 'imenu-list-entry-face-0 nil :foreground 'unspecified :inherit 'markdown-header-face-1)
  (set-face-attribute 'imenu-list-entry-face-1 nil :foreground 'unspecified :inherit 'markdown-header-face-2)
  (set-face-attribute 'imenu-list-entry-face-2 nil :foreground 'unspecified :inherit 'markdown-header-face-3)
  (set-face-attribute 'imenu-list-entry-face-3 nil :foreground 'unspecified :inherit 'markdown-header-face-4)
```

**Comment by protesilaos** [comment]
Hello @newhallroad and Happy New Year!

> Thank you for your magnificent work on emacs. I use your work more or less every day and I appreciate your packages and your meticulous documentation.

You are welcome!

> [...] but perhaps you would be interested in making a more sustainable fix in the ef-themes code.

Yes, sure! I just made a change. I am mimicking what I do with the `modus-themes`. Please let me know if that works for you.

**Comment by newhallroad** [comment]
Wow, you are very quick. Thank you.
The colors are still not quite right, but I think I know why. Awkwardly, markdown-mode starts numbering header faces from `markdown-header-face-1` but imenu-list-mode starts from `imenu-list-entry-face-0`. So I believe `imenu-list-entry-face-[n]` should be the same as `markdown-header-face-[n+1]`. Currently I don't think that off-set is taken into account in ef-themes. Hopefully that's an easy fix.

**Comment by protesilaos** [comment]
> From: newhallroad ***@***.***>
> Date: Tue,  2 Jan 2024 09:20:11 -0800
>
> Wow, you are very quick. Thank you.

You are welcome!

> The colors are still not quite right, but I think I know why.
> Awkwardly, markdown-mode starts numbering header faces from
> `markdown-header-face-1` but imenu-list-mode starts from
> `imenu-list-entry-face-0`. So I believe `imenu-list-entry-face-[n]`
> should be the same as `markdown-header-face-[n+1]`. Currently I don't
> think that off-set is taken into account in ef-themes. Hopefully
> that's an easy fix.

Very well! I pushed an update. Please let me know if it works for you.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by newhallroad** [comment]
That's it! Solved! Thank you!
