### ISSUE TITLE
how to override black color?

### ISSUE THREAD

**Issue by wybryk-ananasa** [protesilaos/ef-themes#37]
I would like to override black color, I would like to make it brighter because it is barely visible in buffer with logs. 
<img width="553" alt="Screenshot 2024-02-14 at 16 05 04" src="https://github.com/protesilaos/ef-themes/assets/144451734/2209a479-a6d1-4d36-86f8-0ba46366dd35">
When I try to override red color all works well:
```
(setq ef-themes-common-palette-overrides
    '((red "#00FF00")))
```
But the same does not work for black:
```
(setq ef-themes-common-palette-overrides
    '((black "#00FF00")))
```
How can I override black color?

**Comment by protesilaos** [comment]
What major mode is this? It seems the themes do not support it. Overriding colours in the palette will not work in this case. We need to support the faces defined by that major mode.

**Comment by wybryk-ananasa** [comment]
This is buffer for process' output, so its major mode is `shell-mode`. 
When I try to print out the face of that black font I get something like this: `(ansi-color-bold (:foreground black))`
I believe that face is already defined in ef-themes.

**Comment by wybryk-ananasa** [comment]
If anyone has a similar problem then this is solution:
```
(require 'ansi-color)
(set-face-attribute 'ansi-color-black nil :background "#B9B4C7" :foreground "#B9B4C7")
```

**Comment by protesilaos** [comment]
Hello @wybryk-ananasa! I just pushed a commit that provides semantic colour mappings that are used by terminal emulators inside of Emacs: https://github.com/protesilaos/ef-themes/commit/4d11f40d46a0edb29047098a989cd58efc2f932a

Though, fundamentally, the themes cannot control which escape sequences are emitted by the terminal. So if the terminal requests "black", the theme does not know if this is a good choice in terms of legibility.
