### ISSUE TITLE
Missing new faces for font-lock, such as font-lock-number-face in Emacs 29

### ISSUE THREAD

**Issue by happyo** [protesilaos/ef-themes#39]
It appears that our repository is lacking support for the font-lock enhancements introduced in Emacs 29. 

https://github.com/emacs-mirror/emacs/blob/c77e35efd36f2c43e87066faa4257606d5c6f849/etc/NEWS.29#L820

**Comment by protesilaos** [comment]
This is on purpose. I do not think numbers or punctuation need a different colour. But I am happy to reconsider if there is a good use-case for those.

**Comment by happyo** [comment]
Thank you for your response! I understand your point of view. 
The reason I brought up this issue is because I want to utilize treesit to enhance some code highlighting that is missing in regular modes. I noticed that the corresponding treesit modes, such as java-ts-mode, do indeed utilize these font locks. I believe many users who employ treesit for code highlighting may have similar needs. Of course, we could also consider adding these functionalities ourselves.

**Comment by protesilaos** [comment]
> From: happyo ***@***.***>
> Date: Sat, 16 Mar 2024 04:31:18 -0700
>
> Thank you for your response! I understand your point of view. The
> reason I brought up this issue is because I want to utilize treesit to
> enhance some code highlighting that is missing in regular modes. I
> noticed that the corresponding treesit modes, such as java-ts-mode, do
> indeed utilize these font locks. I believe many users who employ
> treesit for code highlighting may have similar needs. Of course, we
> could also consider adding these functionalities ourselves.

Maybe you can show me some examples? We can always cover those, if
needed.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by happyo** [comment]
The following two images depict Dart language code. The first image shows the theme displayed in VSCode, while the second image showcases my usage of the "ef-summer" theme with some personalized color modifications.

I'm interested in highlighting certain elements, as indicated in my annotated areas in the images. I believe this enhancement could greatly improve the visual appeal of the code. However, the standard dart-mode lacks these features, necessitating the use of treesit for syntax analysis and subsequent highlighting.

In my opinion, utilizing distinct colors for parentheses and numbers would enhance the overall readability and aesthetics of the code.
<img width="354" alt="截屏2024-03-16 20 16 52" src="https://github.com/protesilaos/ef-themes/assets/10767449/6db32b50-1a3b-422c-9f25-1c60e4682c84">
<img width="430" alt="截屏2024-03-16 20 04 17" src="https://github.com/protesilaos/ef-themes/assets/10767449/9ab136e6-ee4b-40bf-8cf1-4e4b5c276ea4">

**Comment by protesilaos** [comment]
Those extra colours for the parentheses remind me of the `rainbow-delimiters` package. Have you tried it? We cannot add differing colours for delimiters directly at the theme level: it requires more code to do it.

Another note is that we must check with the major mode to confirm it uses those faces. To do this, you have to place the cursor of the character you are interested in and do `M-x describe-char`. In the resulting Help buffer, check if there is a reference to a face.

**Comment by happyo** [comment]
Thank you very much for mentioning the `rainbow-delimiters` package. I've tried it out and found it to be excellent. Upon inspection using `describe-char` I noticed that the face is set to default, likely because my major mode is `dart-mode`. However, upon switching to `dart-ts-mode`, the previous syntax highlighting rules seem to change. Unfortunately, I'm unable to display the highlighting, possibly due to some bugs. 

Upon examining the code within `dart-ts-mode--font-lock-settings`, I noticed the utilization of the previously mentioned new font lock features. You can find the code here: [dart-ts-mode.el](https://github.com/50ways2sayhard/dart-ts-mode/blob/main/dart-ts-mode.el). 

Nevertheless, with the use of `rainbow-delimiters` I find the styling to be sufficient for my needs, and I may not necessarily need to rely on dart-ts-mode.
