### ISSUE TITLE
doom-modeline-urgent cropped icon

### ISSUE THREAD

**Issue by fargiolas** [protesilaos/ef-themes#42]
Seeing this with ef-dream but that's probably in common with all the ef-themes (and maybe modus?).

The icon next to the flymake error count in doom-modeline is slanted and the right part is slightly cropped.
Probably depends on the combination of fonts and icons? screenshot is from master with Menlo and nerd icons.

Same does not happen inheriting from `bold` instead of `bold-italic`. 

I think the real problem is doom applying the same face to text and icon and italic icon not making much sense, but maybe we could live without the italic at all? I guess icon and color already convey the urgency?

<img width="166" alt="ef-dream" src="https://github.com/protesilaos/ef-themes/assets/133750/552decac-e6d5-44af-b41e-478500617b67">

Thanks! (and thanks for the all the beautiful themes, especially the new ef-reverie and ef-dream, love them! thanks for everything you do!)

**Comment by protesilaos** [comment]
Thank you @fargiolas!

I just pushed an update that removes the bold-italic.
