### ISSUE TITLE
Some `forge` faces use conflicting attributes for private status hide public state attributes

### ISSUE THREAD

**Issue by Lenbok** [protesilaos/ef-themes#47]
First up, thank you for these themes!

The forge author intends that the faces responsible for topic "private status" (unread / pending / done) should only comprise attributes that are orthhogonal to the face attributes used for "public state" (open / closed / merged, etc), so that they can be combined together without losing visual information. E.g., see the face doc string for `forge-topic-unread`
```
  "Face used for summaries of entities with unread notifications.
This face is always used together with, and takes preference
over, a `forge[-fancy]-{issue,pullreq}-STATE' face and should not
specify any attribute that is specified by any of those faces.
Likewise those faces should not set `:weight' or `:slant'."
```

Currently, ef-themes (and possibly modus, I haven't checked), for both `forge-topic-unread` and `forge-topic-done` set the foreground color, masking the foreground color settings for the public state aspect.

For context, see https://github.com/magit/forge/discussions/719#discussioncomment-10987847

**Comment by protesilaos** [comment]
> From: Len Trigg ***@***.***>
> Date: Sat, 19 Oct 2024 14:08:48 -0700
>
> First up, thank you for these themes!

You are welcome!

> The forge author intends that the faces responsible for topic "private
> status" (unread / pending / done) should only comprise attributes that
> are orthhogonal to the face attributes used for "public state" (open /
> closed / merged, etc), so that they can be combined together without
> losing visual information. E.g., see the face doc string for
> `forge-topic-unread`

> [... 14 lines elided]

Can you please load the theme and then evaluate this?

    (ef-themes-with-colors
     (custom-set-faces
      `(forge-dimmed ((,c :inherit shadow)))
      `(forge-issue-completed ((,c :inherit shadow)))
      `(forge-issue-open (( )))
      `(forge-issue-unplanned ((,c :inherit forge-dimmed :strike-through t)))
      `(forge-post-author ((,c :inherit bold :foreground ,name)))
      `(forge-post-date ((,c :inherit bold :foreground ,date-common)))
      `(forge-pullreq-merged ((,c :foreground ,fg-alt)))
      `(forge-pullreq-open ((,c :foreground ,info)))
      `(forge-pullreq-rejected ((,c :foreground ,err :strike-through t)))
      `(forge-topic-done (( )))
      `(forge-topic-pending ((,c :inherit italic)))
      `(forge-topic-slug-completed ((,c :inherit forge-dimmed)))
      `(forge-topic-slug-open ((,c :inherit forge-dimmed)))
      `(forge-topic-slug-saved ((,c :inherit success)))
      `(forge-topic-slug-unplanned ((,c :inherit forge-dimmed :strike-through t)))
      `(forge-topic-unread ((,c :inherit bold)))))

Does it get the desired result?

[ Note that I do not use a box for the unread. It does not look nice and
  we do not use that metaphor anywhere else. Whereas bold is used for
  unread emails, for example. ]

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Lenbok** [comment]
Hi, this does not quite get the intended result, as for me the forge-topic-pending shows as both italic and a yellowish color (I'm using ef-elea-dark):

![image](https://github.com/user-attachments/assets/9f141c68-1681-4edd-b43f-a2b67372793d)

Presumably this is because the effects are additive to those defined in the base theme?

**Comment by protesilaos** [comment]
> From: Len Trigg ***@***.***>
> Date: Sun, 20 Oct 2024 12:55:09 -0700
>
> Hi, this does not quite get the intended result, as for me the
> forge-topic-pending shows as both italic and a yellowish color (I'm
> using ef-elea-dark):
>
> ![image](https://github.com/user-attachments/assets/9f141c68-1681-4edd-b43f-a2b67372793d)
>
> Presumably this is because the effects are additive to those defined in the base theme?

Oh, right! They are added on top. Let me just push the changes and you
can check again. Then we modify them accordingly.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by Lenbok** [comment]
This seems to work fine now, so closing. Thanks!
