### ISSUE TITLE
Org-mode habit column: exclamation mark in dark themes is hard to distinguish

### ISSUE THREAD

**Issue by Spike-Leung** [protesilaos/ef-themes#5]
![ef-auturm](https://user-images.githubusercontent.com/30440218/185661724-112c886c-4439-4376-839f-47ef31cf9a42.png)
![ef-deuteranopia-dark](https://user-images.githubusercontent.com/30440218/185662476-69530e16-e17f-479c-8875-ddfd450962d6.png)

Exclamation mark in habit column is little hard to distinguish.

`dark`, `night`, `autumn`, `winter`, `deuteranopia-dark`  are behave the same.

(Have been updated to 20efd1dea617534ca1e332e07edf18e9f2612045)

Thanks your great work :)

**Comment by protesilaos** [comment]
Hello @Spike-Leung!

The `org-habit` graph is not supported yet.  I will do it as soon as posible.

**Comment by Spike-Leung** [comment]
> 

Get it, thanks~

Should I close the issue ?

**Comment by protesilaos** [comment]
No need to close it.  Let's wait until I add the feature and you can also test it as well to make sure it is okay.  Thank you!

**Comment by protesilaos** [comment]
Just added support for org-habit.  Please give it a try and let me know if it works for you.

**Comment by Spike-Leung** [comment]
It works，thanks！
