### ISSUE TITLE
No face defined for neotree, but face customization not working

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [protesilaos/ef-themes#50]
I have selected the theme to be used from the `*Custom Themes*` buffer like so:

![image](https://github.com/user-attachments/assets/a02bdab5-3fcb-4cbd-9f6f-8615905572b8)

That means, I did not put any code for activating the theme in my `init.el` file as described here: https://github.com/protesilaos/ef-themes/issues/16#issuecomment-1242558568.

I have the following code to customize faces of neotree:

```elisp
(defun customize-neotree ()
  "Customize neotree faces"
  (custom-theme-set-faces
   'user
   '(neo-dir-link-face
     ((((background dark)) (:foreground "DeepSkyBlue"))
      (t                   (:foreground "MediumBlue"))))))

(add-hook 'ef-themes-after-load-theme-hook #'customize-neotree)
```

Could it be that this does not get triggered, because of the way I selected the theme? (via the menubar: Options -> Customize Emacs -> Custom Themes)

**Comment by protesilaos** [comment]
> Could it be that this does not get triggered, because of the way I selected the theme?

Yes, this is the reason. The hook is called by the function `ef-themes-load-theme`.

This should work with any theme, though it requires Emacs 29 or higher:

```elisp
(defun customize-neotree (&rest _)
  "Customize neotree faces"
  (custom-theme-set-faces
   'user
   '(neo-dir-link-face
     ((((background dark)) (:foreground "DeepSkyBlue"))
      (t                   (:foreground "MediumBlue"))))))

(add-hook 'enable-theme-functions #'customize-neotree)
```

**Comment by ZelphirKaltstahl** [comment]
Thank you for replying this quickly and especially on this day!

Tested your snippet, and it does work. Thank you!

**Comment by protesilaos** [comment]
> From: Zelphir Kaltstahl ***@***.***>
> Date: Tue, 31 Dec 2024 06:09:29 -0800
>
> Thank you for replying this quickly and especially on this day!
>
> Tested your snippet, and it does work. Thank you!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
