### ISSUE TITLE
`ef-themes-select` do not show the full list of themes after `load-theme`

### ISSUE THREAD

**Issue by jeanphilippegg** [protesilaos/ef-themes#6]
With an empty init file, after executing this:

```elisp
(require 'ef-themes)
(load-theme 'ef-summer t)
```
`ef-themes-select` does not show the full list of ef-themes. Also `ef-themes-load-random` does not have the full list either.

Tested with versions 0.2.0 and 0.3.0.

**Comment by protesilaos** [comment]
Hello @jeanphilippegg!  Version 0.2.0 was [known to have this bug](https://github.com/protesilaos/ef-themes/issues/2) though I thought I had fixed it.  Let me look into it and report back to you.

**Comment by protesilaos** [comment]
Just pushed commit `9c66a79`.  It should fix the problem.  Tried it with:

```elisp
(require 'ef-themes)

(defun ef-themes--enable-themes ()
  "Enable all Ef themes."
  (mapc (lambda (theme)
          (unless (memq theme custom-known-themes)
            (load-theme theme :no-confirm :no-enable)))
        ef-themes-collection))

(defun ef-themes--list-known-themes ()
  "Return list of `custom-known-themes' with ef- prefix."
  (ef-themes--enable-themes)
  (seq-filter
   (lambda (theme)
     (string-prefix-p "ef-" (symbol-name theme)))
   custom-known-themes))

(load-theme 'ef-summer t)
```

**Comment by protesilaos** [comment]
If you think this fixes it, I will bump the version to `0.3.1` to trigger the rebuild of the package.

**Comment by jeanphilippegg** [comment]
> If you think this fixes it, I will bump the version to `0.3.1` to trigger the rebuild of the package.

I am not familiar with the code, but I tested your solution and it works for me!

**Comment by protesilaos** [comment]
Thank you!  Bumped to version `0.3.1` and now waiting for GNU ELPA to rebuild the package.

**Comment by jeanphilippegg** [comment]
Thanks!
