### ISSUE TITLE
current line number face has scaling issues when adjusting text scaling

### ISSUE THREAD

**Issue by anthonychavezdev** [protesilaos/ef-themes#7]
All ef-themes have a bug that causes the current line number in display-line-numbers-mode to shrink when text scale is being increased, and grow when text-scale is being decreased. I'm not familiar with faces in Emacs, but while trying to fully understand the issue in order to accurately describe it, I found that the issue was that line-number-current-line inherits the bold face, but not the line-number face. Changing ``(line-number-current-line ((,c :inherit bold :foreground ,fg-intense)))`` to ```(line-number-current-line ((,c :inherit (bold line-number) :foreground ,fg-intense)))``` fixes the issue. I discovered this by looking at the modus-themes, as they don't have this bug.

**Comment by protesilaos** [comment]
Thank you @anthonychavezdev!  This was an omission from my side.  Applied the change in commit `69cd079`.
